services:

  db:
    image: 'mysql:latest'
    container_name: 'DB_House_Controller'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
    restart: always
